<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WinForms" Version="3.9.3" />
    <PackageReference Include="log4net" Version="3.3.1" />
    <PackageReference Include="NetVips" Version="3.2.0" />
    <PackageReference Include="NetVips.Native.win-x64" Version="8.18.2" />
    <PackageReference Include="NReco.VideoConverter" Version="1.2.1" />
    <PackageReference Include="NReco.VideoInfo" Version="1.2.1" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.21" />
  </ItemGroup>

</Project>